[tool.poetry]
name = "aiogramprojecttemplate"
version = "0.1.0"
description = ""
authors = ["taimaskhanov11 <81189712+taimaskhanov11@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
PyYAML = "^6.0"
APScheduler = "^3.9.1"
cachetools = "^5.2.0"
pydantic = "^1.10.2"
aiogram = { version = ">=3.0.0b5", allow-prereleases = true }
glqiwiapi = { version = "^2.18.2", optional = true }
aiogram-admin = { git = "https://github.com/taimast/aiogram-admin.git" }
fluentogram = "^1.1.6"
watchdog = "^2.3.0"
sqlalchemy = "^2.0.9"
asyncpg = "^0.27.0"
sqlalchemy-utils = "^0.41.0"
psycopg2 = "^2.9.6"



[tool.poetry.dev-dependencies]

[tool.poetry.extras]
qiwi = ["glqiwiapi"]

[tool.poetry.group.dev.dependencies]
jinja2 = "^3.1.2"
pygithub = "^1.58.1"
paramiko = "^3.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
