[tool.poetry]
name = "aiogramtemplate"
version = "0.1.0"
description = ""
authors = ["taimast <charlskenno@gmail.com>"]


[tool.poetry.dependencies]
python = ">=3.11,<4.0"
uvloop = { version = ">=0.17.0", markers = "sys_platform != 'win32'" }
loguru = "^0.7.0"
PyYAML = "^6.0"
aiogram = {version = "^3.3.0", allow-prereleases = true}
APScheduler = {version = "^4.0.0a4", allow-prereleases = true}
pydantic = "^2.0.3"
fluentogram = "^1.1.6"
sqlalchemy = "^2.0.9"
psycopg2 = "^2.9.6"
aiosqlite = "^0.19.0"
pydantic-settings = "^2.0.2"
alembic = "^1.13.0"
cachetools = "^5.3.2"

[tool.poetry.group.dev.dependencies]
watchdog = "^3.0.0"
sqlalchemy-utils = "^0.41.1"

[tool.poetry.extras]
qiwi = ["glqiwiapi"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
