[tool.poetry]
name = "aiogramtemplate"
version = "0.1.0"
description = ""
authors = ["taimast <charlskenno@gmail.com>"]
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
uvloop = { version = ">=0.17.0", markers = "sys_platform != 'win32'" }
aiogram = "^3.7.0"
pydantic = "^2.7.1"
loguru = "^0.7.0"
PyYAML = "^6.0"
APScheduler = { version = "^4.0.0a4", allow-prereleases = true }
fluentogram = "^1.1.6"
sqlalchemy = "^2.0.9"
psycopg2 = "^2.9.6"
aiosqlite = "^0.19.0"
pydantic-settings = "^2.0.2"
alembic = "^1.13.0"
cachetools = "^5.3.2"
glqiwiapi = {git = "https://github.com/dipwave/glQiwiApi.git"}
yoomoney = "^0.1.0"
requests = "^2.31.0"
bs4 = "^0.0.2"
lxml = "^5.1.0"
stripe = "^8.7.0"
aaioapi = "^2.5.6"
pypayment = "^1.7.14"
pycryptopay-sdk = {git = "https://github.com/taimast/pyCryptoPayAPI.git"}

[tool.poetry.group.dev.dependencies]
watchdog = "^3.0.0"
sqlalchemy-utils = "^0.41.1"
jurigged = "^0.5.7"

[tool.poetry.extras]
qiwi = ["glqiwiapi"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
