[tool.poetry]
name = "aiogramprojecttemplatev4"
version = "0.1.0"
description = ""
authors = ["taimaskhanov11 <81189712+taimaskhanov11@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
tortoise-orm = {extras = ["asyncpg"], version = "^0.19.2"}
PyYAML = "^6.0"
APScheduler = "^3.9.1"
cachetools = "^5.2.0"
pydantic = "^1.10.2"
aiogram = {version = "^3.0.0b5", allow-prereleases = true, extras = ["i18n"]}
glqiwiapi = {version = "^2.18.2", optional = true}
fluent-runtime = "^0.3.1"




[tool.poetry.dev-dependencies]

[tool.poetry.extras]
qiwi = ["glqiwiapi"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
