[tool.poetry]
name = "aiogramprojecttemplate"
version = "0.1.0"
description = ""
authors = ["taimast <charlskenno@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.11"
loguru = "^0.7.0"
PyYAML = "^6.0"
APScheduler = {version = "^4.0.0a3", allow-prereleases = true}
cachetools = "^5.2.0"
pydantic = "^2.0.3"
aiogram = { version = "^3", allow-prereleases = true }
fluentogram = "^1.1.6"
sqlalchemy = "^2.0.9"
asyncpg = "^0.27.0"
psycopg2 = "^2.9.6"
pre-commit = "^3.3.2"
aiosqlite = "^0.19.0"
pydantic-settings = "^2.0.2"

[tool.poetry.group.utils.dependencies]
watchdog = "^3.0.0"
sqlalchemy-utils = "^0.41.1"

[tool.poetry.group.dev.dependencies]
jinja2 = "^3.1.2"
pygithub = "^1.58.1"
paramiko = "^3.1.0"
sshtunnel = "^0.4.0"
fabric = "^3.0.1"
decorator = "^5.1.1"
invocations = "^3.1.0"
msgspec = "^0.15.1"
pyrogram = "^2.0.106"
asyncache = "^0.3.1"

[tool.poetry.extras]
qiwi = ["glqiwiapi"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
