bot:
  token: your_token
  admins:
    - 000000000
db:
  user: postgres
  password: postgres
  database: crying
  host: localhost
  port: 5432



#webhook:
#  domain: 195.22.712.246:8443
#  port: 8443
#

## create certificate - `openssl req -newkey rsa:2048 -sha256 -nodes -keyout private.key -x509 -days 3650 -out cert.pem`
#  ssl_cert:
#    certfile: cert.pem
#    keyfile: private.key

merchant:
  crypto_cloud:
    shop_id: your_shop_id
    api_key:  your_api_key

  yookassa:
    shop_id: 123123
    api_key: your_api_key

#  qiwi:
#    api_key: your_token