name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello World"

      - name: Print2
        run: echo "Hello World"
