name: Build and Deploy to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python-ckecks:
    runs-on: ubuntu-latest
    steps:
      - name: PyCharm Python Security Scanner
        uses: tonybaloney/pycharm-security@1.25.1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
